const LOGIN_HTML=`<div class="box"><h3>Sign in to FRAUD//CONTROL</h3>
<form id="lf" onsubmit="event.preventDefault();login()">
<label>Email<input type="email" id="lemail" required autocomplete="username"></label>
<label>Password<input type="password" id="lpass" required autocomplete="current-password"></label>
<label>Role<select id="lrole"><option value="viewer">Viewer</option><option value="analyst">Analyst</option><option value="admin">Admin</option></select></label>
<div class="row-f"><button type="submit" class="p">Sign in</button></div>
<div id="lerr" class="tag crit" style="display:none"></div></form></div>`;

const PAGES=[
["start","Start Here","0",["overview","What FRAUD//CONTROL is and the first things to try"],
 {"what":"Your entry point: a short, task-oriented map of the whole console.",
  "how":["Pick a task below or press its hotkey.","Or open the Command Palette (Cmd+K) and type."],
  "controls":"Each card links directly to the view it describes.",
  "calm":"All health dots green; baseline drift < 5%; bus lag < 50 ms.",
  "worry":"Any component shows red or baseline drift > 15%.",
  "tips":["Bookmark #/start to land here after login.","Press ? anywhere for contextual help."],
  "related":["cmd","alerts","analytics"]}],
["cmd","Command Center","1",["overview","Live traffic, triage queue, and system health"],
 {"what":"Real-time stream of decisions with instant drill-down.",
  "how":["Watch the feed.","Click a row -> event drawer.","Filter by level / campaign / user."],
  "controls":"Pause toggles live updates. Filters persist in the URL.",
  "calm":"Steady flow; CRITICAL < 1% of traffic.",
  "worry":"Sudden spike in CRITICAL or bus lag > 200 ms.",
  "tips":["Shift-click to open multiple drawers.","Drag the drawer edge to resize."],
  "related":["alerts","user","logs"]}],
["alerts","Alert Center","2",["overview","Every HIGH / CRITICAL decision that crossed the alert threshold"],
 {"what":"Curated list of events that need human attention.",
  "how":["Open an alert -> investigation.","Mark acknowledged / resolved.","Block all entities from an incident."],
  "controls":"Filter by status, level, time. Column sort by clicking headers.",
  "calm":"Alert rate matches baseline; most alerts get acknowledged within SLA.",
  "worry":"Alert flood or many unacknowledged > 30 min.",
  "tips":["Use the incident link to see the full cluster.","Bulk-acknowledge from the API."],
  "related":["cmd","incidents","user"]}],
["user","Investigations","3",["investigation","Per-user and per-alert deep dives"],
 {"what":"Full context for one identity: timeline, graph, recommendations, block actions.",
  "how":["Search a user id.","Switch between Event / Graph / Recommendations tabs.","Block / unblock entities."],
  "controls":"Tabs keep their state in the URL. Time window selector top-right.",
  "calm":"Single user, low risk, no graph clusters.",
  "worry":"Multiple devices / IPs / campaigns; graph cluster size > 10.",
  "tips":["Graph shows shared device / IP / subnet edges.","Export the report as JSON."],
  "related":["alerts","incidents","cmd"]}],
["incidents","Incidents","4",["analysis","Merged clusters of related HIGH / CRITICAL activity"],
 {"what":"Automatic correlation: same user / device / IP / subnet / campaign-attack window.",
  "how":["Open an incident -> combined view.","Block all entities with one click.","Watch the timeline for recurrence."],
  "controls":"Status filter (open / closed). Click an incident id for the detail page.",
  "calm":"Incidents close after 5 min of inactivity; no new merges.",
  "worry":"Incident keeps re-opening; campaign+attack merge fires repeatedly.",
  "tips":["Incident summary lists top reasons and rules.","Block-all records the incident id on every entity."],
  "related":["alerts","user","combined","patterns"]}],
["analytics","Combined Analysis","5",["analysis","Cross-layer signal merge: worst clusters, totals, trend"],
 {"what":"One screen that groups every suspicious decision by its strongest shared attribute.",
  "how":["Pick a time window.","Sort clusters by peak risk or volume.","Drill into a cluster -> incident or user."],
  "controls":"Min-risk slider; time window; limit selector.",
  "calm":"Few clusters, low peak risk, steady timeline.",
  "worry":"A single cluster dominates volume or risk; trend climbing.",
  "tips":["Clusters use campaign -> advert -> device -> fallback.","Export clusters as CSV."],
  "related":["incidents","target","search"]}],
["target","Targeted Analysis","6",["analysis","Who is being targeted, which campaigns, and the cost"],
 {"what":"Victim-centric view: high-risk users, the campaigns hitting them, and clean traffic for contrast.",
  "how":["Adjust the look-back window.","Click a victim -> investigation.","Compare wasted vs clean spend."],
  "controls":"Since-minutes; limit. Campaign filter via URL.",
  "calm":"Wasted clicks near zero; victims list empty.",
  "worry":"Many victims; wasted clicks rising; clean campaigns contaminated.",
  "tips":["Wasted spend is a proxy for budget loss.","Save the view as a recurring report."],
  "related":["combined","campaigns","search"]}],
["campaigns","Campaign Analytics","7",["analysis","Campaign-level performance and risk breakdown"],
 {"what":"Aggregate stats per campaign: clicks, users, risk, criticals.",
  "how":["Sort by criticals to find the riskiest campaigns.","Drill into a campaign -> targeted analysis."],
  "controls":"Time window; sort columns.",
  "calm":"All campaigns low risk; criticals zero.",
  "worry":"A campaign has > 5% critical rate or sudden volume jump.",
  "tips":["Cross-reference with the advertiser's own dashboards.","Use the campaign id in targeted analysis."],
  "related":["target","combined","search"]}],
["logs","Event Logs","8",["analysis","Searchable, filterable log of every decision"],
 {"what":"Raw decision feed with full filters: level, user, campaign, source, run id, free text.",
  "how":["Apply filters.","Click a row -> event drawer.","Export visible rows as CSV."],
  "controls":"All filters persist in the URL. Pagination via limit / before cursor.",
  "calm":"Expected volume; familiar distributions.",
  "worry":"Sudden new source / run id; level distribution shifts.",
  "tips":["Combine level=CRITICAL with campaign to isolate a burst.","Save the filter URL for recurring checks."],
  "related":["cmd","analytics","saved"]}],
["patterns","Pattern Library","9",["analysis","Analyst-authored signatures that label (never block) recurring schemes"],
 {"what":"Saved patterns classify HIGH/CRITICAL decisions. Two+ conditions required; max 200 patterns.",
  "how":["Create a pattern from the built-in conditions or custom numeric rules.","Preview against history before saving.","Hits are counted per pattern."],
  "controls":"Name / description / action (label / alert). Condition builder with field / op / value.",
  "calm":"Patterns match known schemes; hit counts stable.",
  "worry":"A pattern suddenly spikes; a built-in condition you disabled is now firing.",
  "tips":["Preview shows up to 10 matching events.","Hits are recorded per event for trend charts."],
  "related":["incidents","analytics","target"]}],
["saved","Saved Attacks","10",["analysis","Named, replayable scenarios for testing and regression"],
 {"what":"Give any simulation a name, notes, tags. Replay at any speed, duplicate, compare, export / import JSON.",
  "how":["Run a simulation -> Save -> name it.","Replay from the list (1x .. 50x).","Compare two runs side by side."],
  "controls":"Name (required), notes, tags. Confirm on delete.",
  "calm":"Saved attacks replay cleanly; level counts match original.",
  "worry":"Replay produces different counts -> schema drift or model change.",
  "tips":["Export JSON to share with other environments.","Import creates a new saved attack automatically."],
  "related":["logs","analytics","cmd"]}],
["search","Search","11",["analysis","One box across users, campaigns, adverts, devices, incidents, alerts"],
 {"what":"Instant cross-index search. Type a user id, campaign, advert, device, incident id, or alert text.",
  "how":["Type in the palette or the search page.","Results grouped by type. Click to jump."],
  "controls":"Debounced; minimum 1 character.",
  "calm":"Query returns expected handful of rows.",
  "worry":"No results for a known id -> data gap or filter issue.",
  "tips":["Press Cmd+K anywhere to open the palette with your query pre-filled.","Results link directly to investigations."],
  "related":["user","campaigns","incidents","alerts"]}],
["models","Model Monitor","12",["ml","Drift, importance, retrain / rollback"],
 {"what":"PSI drift, feature importance, version history, one-click retrain or rollback.",
  "how":["Watch the drift bar.","Retrain when PSI > 0.2.","Rollback if new version degrades."],
  "controls":"Baseline reset button (admin only).",
  "calm":"PSI < 0.1; importance stable.",
  "worry":"PSI > 0.2 or retrain fails validation.",
  "tips":["Retrain uses the same split config; version bump is automatic.","Rollback is instant and audited."],
  "related":["pipeline","settings"]}],
["pipeline","Pipeline","13",["ml","Layer status, weights, latency, quality gates"],
 {"what":"Live component health: rules, ML, anomaly, graph, online; weights and latency per layer.",
  "how":["Watch component states.","Renormalised weights shown when a layer fails.","Quality gate pass / fail."],
  "controls":"Refresh interval top-right.",
  "calm":"All green; weights near default; latency p95 < 30 ms.",
  "worry":"Any component degraded; ML weight dropped to 0.",
  "tips":["System events log every component flip.","Online learner window size in settings."],
  "related":["models","cmd","settings"]}],
["blocklist","Blocklist","14",["admin","Manual and automatic blocks with reasons"],
 {"what":"Every active block: entity type, id, reason, score, who/when, incident link.",
  "how":["Filter by type / source.","Unblock (confirm).","See which incident caused an auto-block."],
  "controls":"Sortable columns; auto-blocks show 'engine' as author.",
  "calm":"Block count stable; reasons clear.",
  "worry":"Rapid growth; many blocks without incident id (orphaned).",
  "tips":["Unblocking clears the in-memory set immediately.","Audit log records every block / unblock."],
  "related":["incidents","alerts","cmd"]}],
["rules","Rules","15",["admin","Rule editor: conditions, weights, activation"],
 {"what":"Create / edit / toggle rules. Each rule has conditions, a weight, and an enabled flag.",
  "how":["Add a rule -> set conditions -> weight -> enable.","Test against recent traffic before enabling.","Disable instead of deleting for history."],
  "controls":"Weight 0..1; condition field / op / value builder.",
  "calm":"Rules fire as expected; no stale rules enabled.",
  "worry":"Many rules fire on the same events (overlap).",
  "tips":["Rules are evaluated before ML; they can force BLOCK.","Export / import rule sets as JSON."],
  "related":["settings","models","pipeline"]}],
["settings","Settings","16",["admin","System, security, AI, retention, login limits"],
 {"what":"Central configuration: risk thresholds, retention windows, login rate, AI provider, keys.",
  "how":["Edit a value -> Save (audited).","Test AI connection before saving.","Reset to defaults via button."],
  "controls":"Inline validation; confirmation on destructive changes.",
  "calm":"All settings saved; AI test green.",
  "worry":"AI test fails; retention too short for compliance.",
  "tips":["Login rate limit is per-minute per IP.","Risk.auto_block toggles engine auto-blocking."],
  "related":["rules","models","pipeline"]}],
["datarst","Data & Reset","17",["admin","Scoped, previewed, audited data clearing"],
 {"what":"Choose exactly what to clear: events, alerts, incidents, recommendations, live state, blocklist, learning, saved attacks, patterns. Presets for network / factory reset. Never clears users, audit, models, API keys.",
  "how":["Open preview -> confirm -> Execute.","Select individual scopes or a preset.","Audit log entry created automatically."],
  "controls":"Preview shows per-scope row counts. Confirm checkbox required.",
  "calm":"Preview counts match expectations; preserved tables untouched.",
  "worry":"Preview shows zero for a scope you expected to clear.",
  "tips":["Factory reset is the only scope that touches blocklist + learning.","Use the CLI script for CI pipelines."],
  "related":["settings","blocklist","saved"]}]
]

// Build VIEWS (for nav rendering) and ROUTES / VIEW_ROUTE from PAGES
const VIEWS=PAGES.map(p=>[p[0],p[1],p[2]])
function navItem(v){return '<a data-v="'+v[0]+'" tabindex="0" onclick="go('+JSON.stringify(v[0])+')" onkeydown="if(event.key===\'Enter\')go('+JSON.stringify(v[0])+')">'+v[1]+'<kbd>'+v[2]+'</kbd></a>'};

const groupOrder=[["overview",["start","cmd","alerts","user"]],["analysis",["incidents","analytics","target","campaigns","logs","patterns","saved","search"]],["ml",["models","pipeline"]],["admin",["blocklist","rules","settings","datarst"]]]